- name: ensure cinder-volume and lvm2 packages are installed
  yum: pkg={{ item }}
  with_items:
    - openstack-cinder
    - lvm2

- name: ensure physical and group volume are created
  lvg: vg=cinder-volumes pvs={{ physical_device }} vg_options=--force
    
- name: ensure cinder.conf is configured
  template: >
    src=../../cinderserver/templates/etc/cinder/cinder.conf
    dest=/etc/cinder/cinder.conf
    owner=cinder group=cinder mode=0640
  notify:
    - restart cinder services

