- name: obtain service tenant id
  shell: >-
    keystone --os-endpoint http://{{ controller_ip }}:35357/v2.0 --os-token \
    {{ admin_token }} tenant-get service|grep id|awk '{print $4}'
  register: nova_admin_tenant_id
    
- name: ensure neutron server and neutron-plugin-ml2 are installed
  yum: pkg={{ item }}
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - python-neutronclient
    - openstack-neutron-openvswitch
    - python-neutron

- name: ensure nova.conf is configured
  template: >
    src=etc/neutron/neutron.conf
    dest=/etc/neutron/neutron.conf
    owner=neutron group=neutron mode=0660
  notify:
    - restart neutron-server

- name: ensure ml2 plugin is configured
  template: >
    src=etc/neutron/plugins/ml2/ml2_conf.ini
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root group=root mode=0644
  notify:
    - restart neutron-server
