- name: Ensure mysql server and mysql python client are installed
  yum: pkg={{ item }}
  with_items:
    - MySQL-python
    - mysql-server

- name: Make sure the mysql service is running
  service: name=mysqld state=started

# http://dev.mysql.com/doc/refman/5.6/en/default-privileges.html
- name: update mysql root password for all root accounts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ root_db_password }}
  with_items:
    - 127.0.0.1
    - localhost
    - "{{ inventory_hostname_short }}"

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: copy .my.cnf file with root password credentials
  template: >
    src=root/.my.cnf
    dest=/root/.my.cnf
    owner=root
    mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - "{{ inventory_hostname_short }}"
    - 127.0.0.1
    - ::1

