- name: restart nova-services
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-compute
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-consoleauth
    - openstack-nova-metadata-api
    - openstack-nova-novncproxy
    - openstack-nova-scheduler
    - openstack-nova-spicehtml5proxy
    - openstack-nova-xvpvncproxy
