- name: ensure cinder packages are installed
  yum: pkg={{ item }}
  with_items:
    - openstack-cinder
    - python-cinder
    - python-cinderclient

- name: ensure cinder sqlite is deleted
  file: dest=/var/lib/cinder/glance.sqlite state=absent
          
- name: ensure cinder.conf is configured
  template: >
    src=etc/cinder/cinder.conf
    dest=/etc/cinder/cinder.conf
    owner=cinder group=cinder mode=0640
  notify:
    - restart cinder services

- name: ensure cinder db is initialized
  command: /usr/bin/cinder-manage db sync
  notify: restart cinder services

