- name: ensure keystone database is present
  mysql_db: name=keystone encoding='utf8'  collation='utf8_general_ci'

- name: ensure keystone database user is present
  mysql_user: >
    name=keystone host={{ item }}
    password={{ keystone_db_password }}
    priv=keystone.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1

- name: ensure glance database is present
  mysql_db: name=glance encoding='utf8' collation='utf8_general_ci'

- name: ensure glance database user is present
  mysql_user: >
    name=glance
    host={{ item }}
    password={{ glance_db_password }}
    priv=glance.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1

- name: ensure cinder database is present
  mysql_db: name=cinder encoding='utf8' collation='utf8_general_ci'

- name: ensure cinder database user is present
  mysql_user: >
    name=cinder
    host={{ item }}
    password={{ cinder_db_password }}
    priv=cinder.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1

- name: ensure nova database is present
  mysql_db: name=nova encoding='utf8' collation='utf8_general_ci'

- name: ensure nova database user is present
  mysql_user: >
    name=nova
    host={{ item }}
    password={{ nova_db_password }}
    priv=nova.*:ALL
  with_items:
    - '%'
    - localhost
      
- name: ensure neutron database is present
  mysql_db: name=neutron encoding='utf8' collation='utf8_general_ci'
    
- name: ensure neutron database user is present
  mysql_user: >
    name=neutron
    host={{ item }}
    password={{ neutron_db_password }}
    priv=neutron.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1
                   
- name: ensure heat database is present
  mysql_db: name=heat encoding='utf8' collation='utf8_general_ci'
    
- name: ensure heat database user is present
  mysql_user: >
    name=heat
    host={{ item }}
    password={{ heat_db_password }}
    priv=heat.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1
                   
- name: ensure trove database is present
  mysql_db: name=trove encoding='utf8' collation='utf8_general_ci'
    
- name: ensure trove database user is present
  mysql_user: >
    name=trove
    host={{ item }}
    password={{ trove_db_password }}
    priv=trove.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1
