#- name: obtain service tenant id
#  shell: >-
#    keystone --os-endpoint http://{{ controller_ip }}:35357/v2.0 --os-token \
#    {{ admin_token }} tenant-get service|grep id|awk '{print $4}'
#  register: nova_admin_tenant_id
    
- name: ensure neutron server and neutron-plugin-ml2 are installed
  yum: pkg={{ item }}
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - python-neutronclient

- name: ensure neutron.conf is configured
  template: >
    src=etc/neutron/neutron.conf.j2
    dest=/etc/neutron/neutron.conf
    owner=neutron group=neutron mode=0660
  notify:
    - restart neutron-server

- name: ensure ml2 plugin is configured
  template: >
    src=etc/neutron/plugins/ml2/ml2_conf.ini.j2
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root group=root mode=0644
  notify:
    - restart neutron-server

- name : create a soft link for plugin.ini
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link

- name: ensure neutron database is reinitialized
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

- name : restart services
  service: name=neutron-server state=restarted

