- name: ensure nova packages are installed
  yum: pkg={{ item }}
  with_items:
    - python-nova
    - python-novaclient
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-nova-scheduler

- name: Make sure the nova services are running and enabled 
  service: name={{ item }} state=started enabled=yes
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-consoleauth
    - openstack-nova-novncproxy
    - openstack-nova-scheduler
    - openstack-nova-xvpvncproxy


- name: ensure nova sqlite is deleted
  file: dest=/var/lib/nova/nova.sqlite state=absent
    

- name: ensure /etc/nova directory is present
  file: path=/etc/nova owner=root group=root mode=0755 state=directory

- name: ensure nova.conf file is present
  template: >
    src=etc/nova/nova.conf.j2
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0660
  notify: 
  - restart nova-services

- name: ensure nova db is initialized
  command: /usr/bin/nova-manage db sync
