---
- name: restart mysql
  service: name=mysqld state=restarted

- name: stop keystone
  service: name=openstack-keystone state=stopped

- name: start keystone
  service: name=openstack-keystone state=started

- name: restart keystone
  service: name=openstack-keystone state=restarted

- name: restart nova-services
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-consoleauth
    - openstack-nova-novncproxy
    - openstack-nova-scheduler
    - openstack-nova-xvpvncproxy

- name: restart neutron-server
  service: name=neutron-server state=restarted

- name: restart ovs-agent
  service: name=neutron-plugin-openvswitch-agent state=restarted
  
- name: restart neutron agents
  service: name=$item state=restarted
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-lbaas-agent
    - neutron-metadata-agent
    
- name: restart openvswitch services
  service: name=openvswitch-switch state=restarted

- name: restart cinder services
  service: name={{ item }} state=restarted
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler

- name: restart web services
  service: name={{ item }} state=restarted
  with_items:
    - httpd
    - memcached

- name: restart glance-services
  service: name={{ item }} state=restarted
  with_items:
    - openstack-glance-registry
    - openstack-glance-api
#    - openstack-glance-scrubber
