- name: ensure br-int switch is created
  openvswitch_bridge: bridge=br-int state=present
  notify: restart ovs agent
  
- name: ensure br-ex switch is created
  openvswitch_bridge: bridge=br-ex state=present
  notify: restart ovs agent

# From /usr/share/doc/neutron-common
- name: ensure br-ex is set as an external bridge
  command: ovs-vsctl br-set-external-id br-ex bridge-id br-ex
  
- name: ensure external interface is added to br-ex
  openvswitch_port: bridge=br-ex port={{ ext_net_nic }} state=present
  notify: restart neutron agents

# Then your br-ex IP address is handled by your network config in your
# /etc/network/interfaces configuration file:

# auto br-ex
# iface br-ex inet static
#         address 192.168.1.10
#         netmask 255.255.255.0

# This will bring up a bridge "br-int" for the internal network, and "br-ex" for
# the network connected to the public internet. Here, 192.168.1.10 is then of
# course your public IP address of the router which will deliver network to your
# virtual machines.

# - name: ensure br-ex is configured and external interface added permanently
#   template: >-
#     src=etc/network/interfaces
#     dest=/etc/network/interfaces
#     owner=root group=root mode=0644
#   notify: restart network

# External bridge configuration (From https://github.com/openstack-ansible/)

- name: ensure script to configure network is in place
  template: >-
    src=etc/network/if-pre-up.d/configure_br-ex
    dest=/etc/network/if-pre-up.d/configure_br-ex
    owner=root
    group=root
    mode=0755

- name: ensure configure script is run at least once
  command: /etc/network/if-pre-up.d/configure_br-ex

# - name: ensure br-ex is active after reboot
#   template: >-
#     src=etc/rc.local
#     dest=/etc/rc.local
#     owner=root
#     group=root
#     mode=0600

- name: ensure neutron database is absent
  mysql_db: name=neutron state=absent

- name: ensure neutron database is present
  mysql_db: name=neutron

- name: ensure neutron database is reinitialized
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

